# Generated by Django 5.0.3 on 2024-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='contextText',
        ),
        migrations.AddField(
            model_name='context',
            name='agentT',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='context',
            name='userT',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
